services:
  # api:
  #   build:
  #     context: .
  #     target: build
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - 4000:4000
  #   command: npm run serve
  #   depends_on:
  #     - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:8-alpine
    container_name: cache
    ports:
      - 6379:6379
# volumes:
#   mongo-data: